Adding a folder for Javad
pointW/helping_hands_website pull request #101
Opened 2024-09-11 21:13 UTC by jaavad

2024-09-11 21:27 UTC, pointW requested changes

2024-09-11 21:27 UTC, pointW commented on content/authors/Javad Moein/avatar.jpg
Can you put your face at the center of your avatar? Please check the preview https://deploy-preview-101--helpinghandslab.netlify.app/

2024-09-11 21:27 UTC, pointW commented on content/authors/Javad Moein/_index.md
> +role: Graduate Student, CS, AI
Can you make your program and major clear? I.e., M.S. student, CS or M.S. student, AI

2024-09-12 00:21 UTC, jaavad commented on content/authors/Javad Moein/avatar.jpg
Sure, I did it- [adding edited Photo]

2024-09-12 00:21 UTC, jaavad commented on content/authors/Javad Moein/_index.md
> +role: Graduate Student, CS, AI
Done

2024-09-12 15:27 UTC, pointW approved these changes

2024-09-12 15:28 UTC, merged